### ISSUE TITLE
How is VGG integrated to sparse coding?

### ISSUE THREAD

**Issue by hnyz979** [phuselab/SSLD-face_recognition#2]
Dear Cuculo:
Thank you for your paper and code. I am very interested in combining CNN's with sparse coding, which I found in figure 1 in our paper. 
However, I did not see where the VGG is implemented and how it is combined with sparse coding in your shared code. Would you kindly tell me about more details?
Thank you~

**Comment by vcuculo** [comment]
@hnyz979 thanks for your interest! The VGG architecture adopted in the paper is the standard pre-trained [VGG-Face](https://www.robots.ox.ac.uk/~vgg/software/vgg_face/). When using the provided `download_data.sh` script it automatically downloads the features characterization from the last fc layer structured as an ad-hoc class ([Dataset](https://github.com/phuselab/SSLD-face_recognition/blob/master/dataset.py)).
These are then used to initialize and learn sub-dictionaries of the proposed method: https://github.com/phuselab/SSLD-face_recognition/blob/f55f408271ac83c728951c918fee9b2e58daf540/main.py#L55

**Comment by hnyz979** [comment]
Thank you for your response!
