### ISSUE TITLE
I ran the code through the steps provided by the author, but there was no result.

### ISSUE THREAD

**Issue by kuaileyuandi** [phuselab/SSLD-face_recognition#3]
I ran the code through the steps provided by the author, but there was no result.

**Comment by aledamelio** [comment]
Hi @kuaileyuandi thank you for the interest in this work!
Could you please be a little bit more specific? What kind of error do you have?

**Comment by kuaileyuandi** [comment]
> 您好@kuaileyuandi，谢谢您对这项工作的关注！
> 您能否更具体一点？你有什么错误？

![image](https://user-images.githubusercontent.com/56589047/112083917-e5c8f200-8bc2-11eb-84c7-0e0610bbc2d4.png)
![3U`E}7CP{L5 )XX 2A~RDXT](https://user-images.githubusercontent.com/56589047/112083943-f0838700-8bc2-11eb-8d84-3bee303ed3dd.png)
Follow the procedure provided by the author and report the following errors

**Comment by aledamelio** [comment]
It seems like sklearn is cannot be found in you system. Please make sure you installed the sklearn version suggested in the requirements section.

**Comment by mi-a-la** [comment]
Dear Aledamelio, best wishes to you. I want to change the dataset, but I don't have the pre-processing code for the dataset. Could you please tell me?Looking forward to your reply as soon as possible!
